#!/usr/bin/env node
// (C) 2018 Harry Dole
// Catecon:  The Categorical Console
//
const AWS = require('aws-sdk');
const fs = require('fs');
const proc = require('child_process');

AWS.config.loadFromPath('/home/hdole/.aws/config.json');

const bldFilename = '.build.json';
const tsFilename = '.timestamps.json';

let lambda = new AWS.Lambda();

fs.readFile(bldFilename, 'utf8', function bldReadFileCB(err, data)
{
	if (err)
	{
		console.log('Error: ', err);
		return;
	}
	const fileInfo = JSON.parse(data);
	const timestamps = {};

	const files = Object.keys(fileInfo);
	//
	// get current timestamps
	//
	files.map(f => timestamps[f] = fs.statSync(f).mtime.getTime());
	//
	// get last deployment state
	//
	fs.readFile(tsFilename, 'utf8', function tsReadFileCB(err, data)
	{
		if (err)
		{
			console.log('Error: ', err);
			return;
		}
		const deployed = JSON.parse(data);
		const deployMe = files.filter(f => timestamps[f] > (f in deployed ? deployed[f] : 0));
		deployMe.map(f =>
			{
				const info = fileInfo[f];
				switch(info.method)
				{
				case 'copyCat':
					const cmd = `scp -i ~/hdole-norcal.pem ${deployMe} ec2-user@ec2-52-8-231-154.us-west-1.compute.amazonaws.com:/var/www/html/${info.target}`;
					process.stdout.write(`${cmd}\n`);
					proc.execSync(cmd);
					break;
				}
			});
		fs.writeFileSync(tsFilename, JSON.stringify(timestamps), 'utf8');
	});
});
